// Generated by Framer (d2515d1)

import { addFonts, addPropertyControls, ComponentViewportProvider, ControlType, cx, CycleVariantState, getFonts, useComponentViewport, useLocaleInfo, useVariantState, withCSS, withMappedReactProps } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { withDarkTheme, withLightTheme, withToggleTheme } from "https://framerusercontent.com/modules/zut3nAIjs6GSSyjpRvZG/mrsIJSHawybQjcu18NhX/ThemeToggle.js";
import ToggleButton, * as ToggleButtonInfo from "./ekNLMjrS_";
import ToggleButtonCopy, * as ToggleButtonCopyInfo from "./EU2E2zxqn";
const ToggleButtonFonts = getFonts(ToggleButton);
const ToggleButtonWithLightThemeWithMappedReactPropsa7nn8f = withMappedReactProps(withLightTheme(ToggleButton), ToggleButtonInfo);
const ToggleButtonCopyFonts = getFonts(ToggleButtonCopy);
const ToggleButtonCopyWithDarkThemeWithMappedReactPropse13ew7 = withMappedReactProps(withDarkTheme(ToggleButtonCopy), ToggleButtonCopyInfo);
const MotionDivWithToggleTheme = withToggleTheme(motion.div);

const cycleOrder = ["iSI9BQRd3"];

const serializationHash = "framer-cvmTY"

const variantClassNames = {iSI9BQRd3: "framer-v-bkbvlv"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion(React.Fragment)

const getProps = ({activeColor, height, id, inactiveColor, width, ...props}) => { return {...props, ap8tRvNEV: activeColor ?? props.ap8tRvNEV ?? "var(--token-7049cce7-715e-45a0-a41e-932274474306, rgb(9, 227, 8))", w0swZ910C: inactiveColor ?? props.w0swZ910C ?? "rgb(115, 115, 115)"} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;activeColor?: string;inactiveColor?: string; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const { activeLocale, setLocale } = useLocaleInfo()

const {style, className, layoutId, variant, ap8tRvNEV, w0swZ910C, FoNgi4rUl, JZRwA9XP6, VoeubVoba, ...restProps} = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({cycleOrder, defaultVariant: "iSI9BQRd3", variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const ref1 = React.useRef<HTMLElement>(null)

const defaultLayoutId = React.useId()

const sharedStyleClassNames = []

const componentViewport = useComponentViewport()

return (<LayoutGroup id={layoutId ?? defaultLayoutId}>
<Variants animate={variants} initial={false}><Transition value={transition1}><MotionDivWithToggleTheme {...restProps} {...gestureHandlers} className={cx(serializationHash, ...sharedStyleClassNames, "framer-bkbvlv", className, classNames)} data-framer-name={"Variant 1"} layoutDependency={layoutDependency} layoutId={"iSI9BQRd3"} ref={ref ?? ref1} style={{borderBottomLeftRadius: 4, borderBottomRightRadius: 4, borderTopLeftRadius: 4, borderTopRightRadius: 4, ...style}}><ComponentViewportProvider ><motion.div className={"framer-18ouysl-container"} layoutDependency={layoutDependency} layoutId={"SnSZmkUX8-container"}><ToggleButtonWithLightThemeWithMappedReactPropsa7nn8f G6irDsNeL={ap8tRvNEV} height={"100%"} id={"SnSZmkUX8"} layoutId={"SnSZmkUX8"} pRHizpZ48={FoNgi4rUl} Q5dMDAlEN={w0swZ910C} style={{height: "100%"}} variant={"jqnypXOwt"} WA8k1PXV8={JZRwA9XP6} width={"100%"}/></motion.div></ComponentViewportProvider><ComponentViewportProvider ><motion.div className={"framer-1cu2i6o-container"} layoutDependency={layoutDependency} layoutId={"LHMLgmEjJ-container"}><ToggleButtonCopyWithDarkThemeWithMappedReactPropse13ew7 G6irDsNeL={ap8tRvNEV} height={"100%"} id={"LHMLgmEjJ"} layoutId={"LHMLgmEjJ"} pRHizpZ48={VoeubVoba} Q5dMDAlEN={w0swZ910C} style={{height: "100%"}} variant={"qE87TD8YV"} WA8k1PXV8={JZRwA9XP6} width={"100%"}/></motion.div></ComponentViewportProvider></MotionDivWithToggleTheme></Transition></Variants>
</LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-cvmTY.framer-1p0p3uw, .framer-cvmTY .framer-1p0p3uw { display: block; }", ".framer-cvmTY.framer-bkbvlv { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 11px; height: min-content; justify-content: center; padding: 0px; position: relative; width: min-content; }", ".framer-cvmTY .framer-18ouysl-container, .framer-cvmTY .framer-1cu2i6o-container { flex: none; height: 40px; position: relative; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-cvmTY.framer-bkbvlv { gap: 0px; } .framer-cvmTY.framer-bkbvlv > * { margin: 0px; margin-left: calc(11px / 2); margin-right: calc(11px / 2); } .framer-cvmTY.framer-bkbvlv > :first-child { margin-left: 0px; } .framer-cvmTY.framer-bkbvlv > :last-child { margin-right: 0px; } }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 40
 * @framerIntrinsicWidth 51
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"ap8tRvNEV":"activeColor","w0swZ910C":"inactiveColor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerdrcOnNd98: React.ComponentType<Props> = withCSS(Component, css, "framer-cvmTY") as typeof Component;
export default FramerdrcOnNd98;

FramerdrcOnNd98.displayName = "ThemeToggle";

FramerdrcOnNd98.defaultProps = {height: 40, width: 51};

addPropertyControls(FramerdrcOnNd98, {ap8tRvNEV: {defaultValue: "var(--token-7049cce7-715e-45a0-a41e-932274474306, rgb(9, 227, 8)) /* {\"name\":\"Primary\"} */", title: "Active Color", type: ControlType.Color}, w0swZ910C: {defaultValue: "rgb(115, 115, 115)", title: "Inactive Color", type: ControlType.Color}} as any)

addFonts(FramerdrcOnNd98, [{explicitInter: true, fonts: []}, ...ToggleButtonFonts, ...ToggleButtonCopyFonts], {supportsExplicitInterCodegen: true})