// Generated by Framer (d2515d1)

import { addFonts, addPropertyControls, ComponentViewportProvider, ControlType, cx, CycleVariantState, getFonts, getPropertyControls, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { Icon as Phosphor } from "https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/CAjjxbTJBxHwH1MagCef/Phosphor.js";
import { Icon as Phosphor1 } from "https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js";
const PhosphorFonts = getFonts(Phosphor);
const Phosphor1Controls = getPropertyControls(Phosphor1);

const cycleOrder = ["qE87TD8YV", "nivPTKoyX"];

const serializationHash = "framer-TB4Ax"

const variantClassNames = {nivPTKoyX: "framer-v-9t1agp", qE87TD8YV: "framer-v-12nnl4t"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion(React.Fragment)

const humanReadableEnumMap = {Bold: "bold", Duotone: "duotone", Fill: "fill", Light: "light", Regular: "regular", Thin: "thin"}

const humanReadableVariantMap = {Active: "nivPTKoyX", InActive: "qE87TD8YV"}

const getProps = ({active, height, icon, id, inActive, weight, width, ...props}) => { return {...props, G6irDsNeL: active ?? props.G6irDsNeL ?? "rgb(255, 255, 255)", pRHizpZ48: icon ?? props.pRHizpZ48 ?? "Moon", Q5dMDAlEN: inActive ?? props.Q5dMDAlEN ?? "rgb(115, 115, 115)", variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "qE87TD8YV", WA8k1PXV8: humanReadableEnumMap[weight] ?? weight ?? props.WA8k1PXV8 ?? "bold"} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;variant?: keyof typeof humanReadableVariantMap;icon?: string;inActive?: string;active?: string;weight?: keyof typeof humanReadableEnumMap; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const { activeLocale, setLocale } = useLocaleInfo()

const {style, className, layoutId, variant, pRHizpZ48, Q5dMDAlEN, G6irDsNeL, WA8k1PXV8, ...restProps} = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({cycleOrder, defaultVariant: "qE87TD8YV", variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const ref1 = React.useRef<HTMLElement>(null)

const defaultLayoutId = React.useId()

const sharedStyleClassNames = []

const componentViewport = useComponentViewport()

return (<LayoutGroup id={layoutId ?? defaultLayoutId}>
<Variants animate={variants} initial={false}><Transition value={transition1}><motion.div {...restProps} {...gestureHandlers} className={cx(serializationHash, ...sharedStyleClassNames, "framer-12nnl4t", className, classNames)} data-framer-name={"InActive"} layoutDependency={layoutDependency} layoutId={"qE87TD8YV"} ref={ref ?? ref1} style={{...style}} {...addPropertyOverrides({nivPTKoyX: {"data-framer-name": "Active"}}, baseVariant, gestureVariant)}><ComponentViewportProvider ><motion.div className={"framer-sbv73q-container"} layoutDependency={layoutDependency} layoutId={"g56O3BiRq-container"}><Phosphor color={Q5dMDAlEN} height={"100%"} iconSearch={"House"} iconSelection={pRHizpZ48} id={"g56O3BiRq"} layoutId={"g56O3BiRq"} mirrored={false} selectByList style={{height: "100%", width: "100%"}} weight={WA8k1PXV8} width={"100%"} {...addPropertyOverrides({nivPTKoyX: {color: G6irDsNeL}}, baseVariant, gestureVariant)}/></motion.div></ComponentViewportProvider></motion.div></Transition></Variants>
</LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-TB4Ax.framer-1yuj4u9, .framer-TB4Ax .framer-1yuj4u9 { display: block; }", ".framer-TB4Ax.framer-12nnl4t { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 32px; justify-content: center; padding: 0px; position: relative; width: min-content; }", ".framer-TB4Ax .framer-sbv73q-container { flex: none; height: 20px; position: relative; width: 20px; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-TB4Ax.framer-12nnl4t { gap: 0px; } .framer-TB4Ax.framer-12nnl4t > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-TB4Ax.framer-12nnl4t > :first-child { margin-left: 0px; } .framer-TB4Ax.framer-12nnl4t > :last-child { margin-right: 0px; } }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 32
 * @framerIntrinsicWidth 20
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","fixed"]},"nivPTKoyX":{"layout":["auto","fixed"]}}}
 * @framerVariables {"pRHizpZ48":"icon","Q5dMDAlEN":"inActive","G6irDsNeL":"active","WA8k1PXV8":"weight"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerEU2E2zxqn: React.ComponentType<Props> = withCSS(Component, css, "framer-TB4Ax") as typeof Component;
export default FramerEU2E2zxqn;

FramerEU2E2zxqn.displayName = "ToggleButton Copy";

FramerEU2E2zxqn.defaultProps = {height: 32, width: 20};

addPropertyControls(FramerEU2E2zxqn, {variant: {options: ["qE87TD8YV", "nivPTKoyX"], optionTitles: ["InActive", "Active"], title: "Variant", type: ControlType.Enum}, pRHizpZ48: Phosphor1Controls?.["iconSelection"] && {...Phosphor1Controls["iconSelection"], defaultValue: "Moon", description: undefined, hidden: undefined, title: "Icon"}, Q5dMDAlEN: {defaultValue: "rgb(115, 115, 115)", title: "InActive", type: ControlType.Color}, G6irDsNeL: {defaultValue: "rgb(255, 255, 255)", title: "Active", type: ControlType.Color}, WA8k1PXV8: Phosphor1Controls?.["weight"] && {...Phosphor1Controls["weight"], defaultValue: "bold", description: undefined, hidden: undefined, title: "Weight"}} as any)

addFonts(FramerEU2E2zxqn, [{explicitInter: true, fonts: []}, ...PhosphorFonts], {supportsExplicitInterCodegen: true})