// Generated by Framer (4458791)

import { addFonts, addPropertyControls, ControlType, cx, getFontsFromSharedStyle, Instance, RichText, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Star from "https://framerusercontent.com/modules/lGjONevu0Qs1ZIO2v8WJ/1BYYnFlgrBf9goxuImJd/dZkd7bSHY.js";
import * as sharedStyle from "../css/rerWrmQ65";

const serializationHash = "framer-ZZ7co"

const variantClassNames = {qDwaIyUEs: "framer-v-zo65t"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion.create(React.Fragment)

const getProps = ({content, height, icon, id, width, ...props}) => { return {...props, GJdJmFCj5: content ?? props.GJdJmFCj5 ?? "GraduationCap", v7319IK7C: icon ?? props.v7319IK7C ?? Star} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;content?: string;icon?: React.ComponentType<any> | undefined; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const fallbackRef = useRef<HTMLElement>(null)

const refBinding = ref ?? fallbackRef

const defaultLayoutId = React.useId()

const { activeLocale, setLocale } = useLocaleInfo()

const componentViewport = useComponentViewport()

const { style, className, layoutId, variant, GJdJmFCj5, v7319IK7C, ...restProps } = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({defaultVariant: "qDwaIyUEs", ref: refBinding, variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const sharedStyleClassNames = [sharedStyle.className]

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition1}><motion.div {...restProps} {...gestureHandlers} className={cx(scopingClassNames, "framer-zo65t", className, classNames)} data-border data-framer-name={"primary"} layoutDependency={layoutDependency} layoutId={"qDwaIyUEs"} ref={refBinding} style={{"--border-bottom-width": "1px", "--border-color": "var(--token-5970a3c6-0f13-482e-8fb6-b8cb7d627b04, rgba(216, 231, 242, 0.07))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", backgroundColor: "var(--token-eb09dbbf-ef85-4b7f-81a5-44e9b062efb7, rgb(4, 7, 13))", borderBottomLeftRadius: 60, borderBottomRightRadius: 60, borderTopLeftRadius: 60, borderTopRightRadius: 60, ...style}}><Instance animated className={"framer-1nserkm"} Component={v7319IK7C} layoutDependency={layoutDependency} layoutId={"lD59XIpNq"} style={{"--1m6trwb": 1, "--21h8s6": "var(--token-f195ea74-7512-4096-8d91-0e7c7e10d0ab, rgb(213, 219, 230))", "--pgex8v": 1.5}}/><RichText __fromCanvasComponent children={<React.Fragment><motion.p className={"framer-styles-preset-1u349i7"} data-styles-preset={"rerWrmQ65"}>GraduationCap</motion.p></React.Fragment>} className={"framer-1x6bqto"} fonts={["Inter"]} layoutDependency={layoutDependency} layoutId={"xSOJ_ShuV"} style={{"--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline"}} text={GJdJmFCj5} verticalAlignment={"top"} withExternalLayout/></motion.div></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-ZZ7co.framer-1dxqqrl, .framer-ZZ7co .framer-1dxqqrl { display: block; }", ".framer-ZZ7co.framer-zo65t { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 6px 12px 6px 12px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-ZZ7co .framer-1nserkm { flex: none; height: var(--framer-aspect-ratio-supported, 17px); position: relative; width: 17px; }", ".framer-ZZ7co .framer-1x6bqto { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ...sharedStyle.css, ".framer-ZZ7co[data-border=\"true\"]::after, .framer-ZZ7co [data-border=\"true\"]::after { content: \"\"; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 29
 * @framerIntrinsicWidth 134
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"GJdJmFCj5":"content","v7319IK7C":"icon"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerVectorSets ["omX0gWFPqDwhaiWwf6ab"]
 */
const FramerrOlsEceWf: React.ComponentType<Props> = withCSS(Component, css, "framer-ZZ7co") as typeof Component;
export default FramerrOlsEceWf;

FramerrOlsEceWf.displayName = "Elements / Badge";

FramerrOlsEceWf.defaultProps = {height: 29, width: 134};

addPropertyControls(FramerrOlsEceWf, {GJdJmFCj5: {defaultValue: "GraduationCap", displayTextArea: false, title: "Content", type: ControlType.String}, v7319IK7C: {defaultValue: {identifier: "module:lGjONevu0Qs1ZIO2v8WJ/1BYYnFlgrBf9goxuImJd/dZkd7bSHY.js:default", moduleId: "lGjONevu0Qs1ZIO2v8WJ"}, setModuleId: "omX0gWFPqDwhaiWwf6ab", title: "Icon", type: ControlType.VectorSetItem}} as any)

addFonts(FramerrOlsEceWf, [{explicitInter: true, fonts: [{family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F", url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116", url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+1F00-1FFF", url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0370-03FF", url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF", url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD", url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB", url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2", weight: "400"}]}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {supportsExplicitInterCodegen: true})