// Generated by Framer (397058d)

import { addFonts, addPropertyControls, ControlType, cx, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";

const cycleOrder = ["SBXWoULB1", "x7uS9b1TG", "qImlC3NoS"];

const serializationHash = "framer-rUdVx"

const variantClassNames = {qImlC3NoS: "framer-v-18v002d", SBXWoULB1: "framer-v-37morx", x7uS9b1TG: "framer-v-1607uk4"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {bounce: 0.2, delay: 0, duration: 0.4, type: "spring"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion.create(React.Fragment)

const humanReadableVariantMap = {Full: "SBXWoULB1", Half: "x7uS9b1TG", None: "qImlC3NoS"}

const getProps = ({height, id, width, ...props}) => { return {...props, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "SBXWoULB1"} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;variant?: keyof typeof humanReadableVariantMap; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const fallbackRef = useRef<HTMLElement>(null)

const refBinding = ref ?? fallbackRef

const defaultLayoutId = React.useId()

const { activeLocale, setLocale } = useLocaleInfo()

const componentViewport = useComponentViewport()

const { style, className, layoutId, variant, ...restProps } = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({cycleOrder, defaultVariant: "SBXWoULB1", ref: refBinding, variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const sharedStyleClassNames = []

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition1}><motion.div {...restProps} {...gestureHandlers} className={cx(scopingClassNames, "framer-37morx", className, classNames)} data-framer-name={"Full"} layoutDependency={layoutDependency} layoutId={"SBXWoULB1"} ref={refBinding} style={{borderBottomLeftRadius: 100, borderBottomRightRadius: 100, borderTopLeftRadius: 100, borderTopRightRadius: 100, ...style}} {...addPropertyOverrides({qImlC3NoS: {"data-framer-name": "None"}, x7uS9b1TG: {"data-framer-name": "Half"}}, baseVariant, gestureVariant)}><motion.div className={"framer-1iktr3p"} data-framer-name={"Filler-grey"} layoutDependency={layoutDependency} layoutId={"L2VMNn2Zd"} style={{backgroundColor: "rgb(194, 194, 194)", borderBottomLeftRadius: 20, borderBottomRightRadius: 20, borderTopLeftRadius: 20, borderTopRightRadius: 20}}/><motion.div className={"framer-1cmswf7"} data-framer-name={"Filler-purple"} layoutDependency={layoutDependency} layoutId={"wNjSLHFNo"} style={{backgroundColor: "var(--token-7049cce7-715e-45a0-a41e-932274474306, rgb(9, 227, 8))", borderBottomLeftRadius: 20, borderBottomRightRadius: 20, borderTopLeftRadius: 20, borderTopRightRadius: 20}}/></motion.div></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-rUdVx.framer-b1u4n6, .framer-rUdVx .framer-b1u4n6 { display: block; }", ".framer-rUdVx.framer-37morx { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 168px; }", ".framer-rUdVx .framer-1iktr3p { flex: 1 0 0px; height: 5px; overflow: hidden; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }", ".framer-rUdVx .framer-1cmswf7 { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; top: 0px; width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 1; }", ".framer-rUdVx.framer-v-1607uk4 .framer-1cmswf7 { width: 50%; }", ".framer-rUdVx.framer-v-18v002d .framer-1cmswf7 { width: 0%; }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 5
 * @framerIntrinsicWidth 168
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"x7uS9b1TG":{"layout":["fixed","auto"]},"qImlC3NoS":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramermnmIirwQK: React.ComponentType<Props> = withCSS(Component, css, "framer-rUdVx") as typeof Component;
export default FramermnmIirwQK;

FramermnmIirwQK.displayName = "Filler";

FramermnmIirwQK.defaultProps = {height: 5, width: 168};

addPropertyControls(FramermnmIirwQK, {variant: {options: ["SBXWoULB1", "x7uS9b1TG", "qImlC3NoS"], optionTitles: ["Full", "Half", "None"], title: "Variant", type: ControlType.Enum}} as any)

addFonts(FramermnmIirwQK, [{explicitInter: true, fonts: []}], {supportsExplicitInterCodegen: true})