// Generated by Framer (d2515d1)

import { addFonts, addPropertyControls, ControlType, cx, CycleVariantState, useActiveVariantCallback, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";

const cycleOrder = ["giz4yYTJn", "at430vW36"];

const serializationHash = "framer-9Rvmu"

const variantClassNames = {at430vW36: "framer-v-1ld6zf9", giz4yYTJn: "framer-v-1av4fzl"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion(React.Fragment)

const humanReadableVariantMap = {Close: "at430vW36", Menu: "giz4yYTJn"}

const getProps = ({height, id, tap, width, ...props}) => { return {...props, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "giz4yYTJn", XKaY3MrGu: tap ?? props.XKaY3MrGu} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;variant?: keyof typeof humanReadableVariantMap;tap?: any; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const { activeLocale, setLocale } = useLocaleInfo()

const {style, className, layoutId, variant, XKaY3MrGu, ...restProps} = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({cycleOrder, defaultVariant: "giz4yYTJn", variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant)

const onTapc2fruv = activeVariantCallback(async (...args) => {
setGestureState({isPressed: false})
if (XKaY3MrGu) {const res = await XKaY3MrGu(...args);
if (res === false) return false;}
})

const ref1 = React.useRef<HTMLElement>(null)

const defaultLayoutId = React.useId()

const sharedStyleClassNames = []

const componentViewport = useComponentViewport()

return (<LayoutGroup id={layoutId ?? defaultLayoutId}>
<Variants animate={variants} initial={false}><Transition value={transition1}><motion.div {...restProps} {...gestureHandlers} className={cx(serializationHash, ...sharedStyleClassNames, "framer-1av4fzl", className, classNames)} data-framer-name={"Menu"} data-highlight layoutDependency={layoutDependency} layoutId={"giz4yYTJn"} onTap={onTapc2fruv} ref={ref ?? ref1} style={{...style}} {...addPropertyOverrides({at430vW36: {"data-framer-name": "Close"}}, baseVariant, gestureVariant)}><motion.div className={"framer-195idzx"} data-framer-name={"Bottom"} layoutDependency={layoutDependency} layoutId={"Y8eu91fC7"} style={{backgroundColor: "rgb(182, 182, 185)", borderBottomLeftRadius: 10, borderBottomRightRadius: 10, borderTopLeftRadius: 10, borderTopRightRadius: 10, rotate: 0}} variants={{at430vW36: {rotate: -45}}}/><motion.div className={"framer-1x62hc"} data-framer-name={"Top"} layoutDependency={layoutDependency} layoutId={"b0GU_P9Ca"} style={{backgroundColor: "rgb(182, 182, 185)", borderBottomLeftRadius: 10, borderBottomRightRadius: 10, borderTopLeftRadius: 10, borderTopRightRadius: 10, rotate: 0}} variants={{at430vW36: {rotate: 45}}}/></motion.div></Transition></Variants>
</LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-9Rvmu.framer-1q4vfm, .framer-9Rvmu .framer-1q4vfm { display: block; }", ".framer-9Rvmu.framer-1av4fzl { cursor: pointer; height: 44px; overflow: hidden; position: relative; width: 44px; }", ".framer-9Rvmu .framer-195idzx { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(62.50000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); }", ".framer-9Rvmu .framer-1x62hc { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(37.50000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); }", ".framer-9Rvmu.framer-v-1ld6zf9.framer-1av4fzl { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 44px); }", ".framer-9Rvmu.framer-v-1ld6zf9 .framer-195idzx, .framer-9Rvmu.framer-v-1ld6zf9 .framer-1x62hc { top: calc(50.00000000000002% - 2px / 2); }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 44
 * @framerIntrinsicWidth 44
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"at430vW36":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"XKaY3MrGu":"tap"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerBM6dW4dQJ: React.ComponentType<Props> = withCSS(Component, css, "framer-9Rvmu") as typeof Component;
export default FramerBM6dW4dQJ;

FramerBM6dW4dQJ.displayName = "Navigation/Menu Icon";

FramerBM6dW4dQJ.defaultProps = {height: 44, width: 44};

addPropertyControls(FramerBM6dW4dQJ, {variant: {options: ["giz4yYTJn", "at430vW36"], optionTitles: ["Menu", "Close"], title: "Variant", type: ControlType.Enum}, XKaY3MrGu: {title: "Tap", type: ControlType.EventHandler}} as any)

addFonts(FramerBM6dW4dQJ, [{explicitInter: true, fonts: []}], {supportsExplicitInterCodegen: true})